In [1]:
import numpy as np

## numpy array

In [2]:
benimliste=[20,30,40]

In [3]:
type(benimliste)

list

In [6]:
np.array(benimliste)

array([20, 30, 40])

In [7]:
matrix=[[10,20,30],[40,50,60],[70,80,90]]

In [8]:
type(matrix)

list

In [9]:
matrix[0][1]

20

In [10]:
np.array(matrix)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## arange

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

## zeros

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [18]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [19]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
np.linspace(1,100,200)

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

## eye

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [24]:
np.random.randn(1,20)

array([[ 0.15092762, -0.10968966,  0.44544246, -1.05959754, -2.14892557,
        -0.19195779, -1.11754947,  0.34894477, -0.72676605,  0.27230973,
         0.67549852, -0.33476832,  0.66035454, -1.42466835,  0.70830072,
         0.00909665,  1.55425712,  0.25959333,  0.60798189,  0.43786979]])

In [25]:
np.random.randn(4,4)

array([[ 1.37286923,  0.56749802, -1.85193992, -1.35170938],
       [-0.56638307, -0.93502109,  0.15094914,  0.48415646],
       [-0.97848839, -1.40172764,  0.61247154,  0.44561555],
       [ 1.50538437,  1.04088581,  0.09988743,  0.17659174]])

In [27]:
np.random.randint(1,30)

1

In [28]:
np.random.randint(1,100,5)

array([44, 21, 99,  6, 47])

In [29]:
benimdizim=np.arange(30)

In [30]:
benimdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
bnrandom=np.random.randint(0,40,5)

In [32]:
bnrandom

array([33,  1, 38, 30,  2])

## dizi method

In [38]:
benimdizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [39]:
benimdizim.max()

29

In [40]:
benimdizim.min()

0

In [41]:
bnrandom.max()

38

In [42]:
bnrandom.min()

1

In [43]:
bnrandom.argmax()

2

In [44]:
bnrandom.argmin()

1

In [49]:
rpdizim=benimdizim.reshape(5,6)

In [50]:
rpdizim.shape

(5, 6)