In [1]:
import numpy as np

In [2]:
benimdizim=np.arange(0,15)

In [3]:
benimdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimdizim[5]

5

In [5]:
benimdizim[3:8]

array([3, 4, 5, 6, 7])

In [6]:
benimdizim[3:8]=-5

In [7]:
benimdizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [8]:
baskadizi=np.arange(0,24)

In [9]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
slicingidizi=baskadizi[4:9]

In [11]:
slicingidizi

array([4, 5, 6, 7, 8])

In [12]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
slicingidizi[:]=700

In [14]:
slicingidizi

array([700, 700, 700, 700, 700])

In [15]:
baskadizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [16]:
ornekdizi=np.arange(0,24)

In [17]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
ornekdizikopya=ornekdizi.copy()

In [19]:
ornekdizikopya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekdizikopyaslicing=ornekdizikopya[3:6]

In [22]:
ornekdizikopyaslicing[:]=800

In [23]:
ornekdizikopyaslicing

array([800, 800, 800])

In [24]:
ornekdizikopya

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [25]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [26]:
bnmliste=[[10,20,30],[40,50,60],[70,80,90]]

In [27]:
bnmmatrix=np.array(bnmliste)

In [28]:
bnmmatrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [29]:
bnmmatrix[0]

array([10, 20, 30])

In [30]:
bnmmatrix[1][2]

60

In [31]:
bnmmatrix[2,1]

80

In [32]:
bnmmatrix[2:,1]

array([80])

In [33]:
ynliste=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [34]:
ynmatrix=np.array(ynliste)

In [35]:
ynmatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ynmatrix[0:,4]

array([ 4,  9, 14, 19, 24])

In [37]:
ynmatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## operasyon

In [38]:
yndizi=np.random.randint(1,100,20)

In [39]:
yndizi

array([27, 73, 64, 92, 71, 42, 74, 94, 45, 14, 57, 16, 19, 51, 26, 28, 97,
       90, 59, 89])

In [40]:
yndizi>24

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [41]:
yndizi

array([27, 73, 64, 92, 71, 42, 74, 94, 45, 14, 57, 16, 19, 51, 26, 28, 97,
       90, 59, 89])

In [42]:
sndizi=yndizi>24

In [43]:
sndizi

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [44]:
yndizi

array([27, 73, 64, 92, 71, 42, 74, 94, 45, 14, 57, 16, 19, 51, 26, 28, 97,
       90, 59, 89])

In [45]:
yndizi[sndizi]

array([27, 73, 64, 92, 71, 42, 74, 94, 45, 57, 51, 26, 28, 97, 90, 59, 89])

In [46]:
yndizi

array([27, 73, 64, 92, 71, 42, 74, 94, 45, 14, 57, 16, 19, 51, 26, 28, 97,
       90, 59, 89])

In [47]:
yndizi[yndizi<24]

array([14, 16, 19])

In [48]:
sondizi=np.arange(0,24)

In [49]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
sondizi+sondizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [51]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [52]:
sondizi*sondizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [53]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
sondizi-sondizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [55]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
sondizi/sondizi

C:\Users\Acer\AppData\Local\Temp\ipykernel_8896\2654503216.py:1: RuntimeWarning: invalid value encountered in divide
  sondizi/sondizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [57]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [58]:
np.sqrt(sondizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [59]:
np.max(sondizi)

23

In [60]:
np.min(sondizi)

0